.TH AX25MOND 8 "30 January 1999" Linux "Linux System Managers Manual"
.SH NAME
ax25mond \- dump the AX.25 network traffic and and provide sockets
where the received data will be retransmitted
.SH SYNOPSIS
.B ax25mond [-v|--version]
.SH DESCRIPTION
.LP
.B Ax25mond
will first read it's configuration file /etc/ax25/ax25mond.conf. It will
then wait for connects on the sockets specified in this file. When
connected, it will transmit all data which it has received on the AX.25
monitor socket.
.SH OPTIONS
.TP 15
.BI "\-v, \-\-version"
Displays the version number and some copyright information.
.SH AUTHOR
Johann Hanne, DH3MB <jonny@baycom.org>
