.TH AX25MOND.CONF 5 "30 January 1999" Linux "Linux Programmer's Manual"
.SH NAME
ax25mond.conf \- Specify the sockets which @@@ax25mond@@@ will provide.
.SH DESCRIPTION
.LP
The
.B ax25mond.conf
file specifies the internet- and unix-sockets which @@@ax25mond@@@(8)
will provide. Example:
.LP
# Create an internet socket on port 1234 where all the
.br
# AX.25 traffic will be transmitted
.br
rxtx *:1234
.br
# Create an unix socket where only the received AX.25
.br
# traffic will be transmitted
.br
rx unix:/var/spool/ax25/monitor
.br
.LP
You may specify up to 5 sockets (definable in ax25mond.c) and @@@ax25mond@@@
will accept up to 50 connects (also definable in ax25mond.c).
.SH FILES
.LP
/etc/ax25/ax25mond.conf
.SH "SEE ALSO"
.BR @@@ax25mond@@@ (8).
