.TH AX25RTD 8 "11 November 2003" Linux "Linux Programmer's Manual"
.SH NAME
ax25rtd \- AX.25 routing daemon
.SH SYNOPSIS
.B ax25rtd
.SH DESCRIPTION
.LP
.B ax25rtd
is a daemon that:
.LP
- emulates the ceased "autorouter" of Linux Kernel AX.25
.br
- sets up ARP entries automagically
.br
- may adjust IP routes and encapsulation mode 
  (although I really do not recomment to use this feature...)
.LP
The "autorouter" is not really an autorouter. It just listens to the AX.25
traffic on your ports and uses this information to setup AX.25 routes. This
can be turned on or off by altering the configuration file
/etc/ax25/ax25rtd.conf.
.LP
Ax25rtd provides a socket /var/ax25/ax25rtd/control which is used for
runtime maintainance through
.B ax25rtctl 
or to set up new routes by other
daemons (a Flexnet router, perhaps?)
.LP
On startup ax25rtd reads the configuration file and afterwards preloads
the caches from the files /var/ax25/ax25rtd/ax25_routes and
/var/ax25/ax25rtd/ip_routes. On SIGTERM or 
.B ax25rtctl --save 
it saves the caches to those files.
.SH FILES
/etc/ax25/ax25rtd.conf
.SH "SEE ALSO"
.BR ax25rtd.conf (5),
.BR ax25rtctl (8).
.LP
.SH AUTHORS
.nf
Joerg Reuter <jreuter@poboxes.com>
.br
Llaus Kudielka OE1KIB
.fi
