.TH RSPORTS 5 "27 August 1996" Linux "Linux Programmer's Manual"
.SH NAME
rsports \- Rose port configuration file.
.SH DESCRIPTION
.LP
.B Rsports
is an ASCII file that contains information about each of the Rose
ports that are to be used. When dealing with a Rose utility such as
.B call,
it takes an optional argument that is the port name. This port name is a
reference to the line within
.B rsports,
which has the same name. The information on each line contains
enough information to bind the command to a particular Rose
interface, this binding is done by matching the address on the line in
.B rsports
with the address of the port set by
.B ifconfig
or
.B rsattach.
.LP
The
.B rsports
file may contain comments that begin with a # in the first column, or a port
description in the following format, each field being delimited by white space:
.sp
.RS
name address description
.RE
.sp
The field descriptions are:
.sp
.RS
.TP 14
.B name
this is the unique Rose port identifier.
.TP 14
.B address
the address of the Rose interface to bind to.
.TP 14
.B description
a free format description of this interface, this field extends to the end
of the line. It may contain spaces.
.RE
.SH FILES
.LP
/etc/ax25/rsports
.SH "SEE ALSO"
.BR call (1),
.BR rose (4),
.BR ifconfig (8),
.BR rsparms (8).
